---
#    bind_mounts:
#      - /var/aegir/backups
#      - /var/lib/mysql

- name: "Copy any existing data in {{ bind_mount_dest }} into mounted volume at {{ bind_mount_src }}."
  synchronize:
    src: "{{ bind_mount_dest }}"
    dest: "{{ bind_mount_src }}"
  delegate_to: "{{ inventory_hostname }}"

- name: "Set up bind mounts for {{ bind_mount_dest }}."
  mount:
    path: "{{ bind_mount_dest }}"
    src: "{{ bind_mount_src }}"
    opts: bind
    state: mounted
    fstype: none
