---
- name: Ensure PHP CLI config directory exists.
  file:
    dest: /etc/php/7.2/cli/conf.d/
    state: directory
  become: yes

- name: Increase PHP CLI memory limit.
  template:
    src: memory_limit.ini.j2
    dest: /etc/php/7.2/cli/conf.d/20-memory_limit.ini
  become: yes
