---
- name: Ensure PHP CLI config directory exists.
  file:
    dest: /etc/php/7.2/cli/conf.d/
    state: directory
  become: yes

- name: Increase PHP CLI memory limit.
  copy:
    content: |
      ; {{ ansible_managed }}
      ;
      ; configuration for increasing PHP CLI memory limit
      ; priority=20
      memory_limit = {{ php_cli_memory_limit }}
    dest: /etc/php/7.2/cli/conf.d/20-memory_limit.ini
  become: yes
